name: JReleaser

description: 'Release Java projects quickly and easily with JReleaser'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:

  version:
    description: 'The version of JReleaser to download and execute.'
    default: 'early-access'
    required: true

  arguments:
    description: 'The command-line arguments to be passed to JReleaser.'
    default: 'full-release'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Download JReleaser'
      shell: bash
      run: |
        echo "::group::Download JReleaser"
        JAR="jreleaser-tool-provider-${{ inputs.version }}.jar"
        URL="https://github.com/jreleaser/jreleaser/releases/download/${{ inputs.version }}/$JAR"
        java "${{ github.action_path }}/copy.java" $URL $JAR
        java -jar $JAR --version
        echo "::endgroup::"
    - name: 'Execute JReleaser'
      shell: bash
      run: |
        JAR="jreleaser-tool-provider-${{ inputs.version }}.jar"
        echo "java -jar $JAR ${{ inputs.arguments }}"
        java -jar $JAR ${{ inputs.arguments }}
